server:
  port: 9090
eu:
  smartclide:
    api:
      host: localhost
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-smartclide-che.che.smartclide.eu/auth/realms/che
  cloud:
    gateway:
      routes:
        # MoM
        - id: mom-rest
          uri: http://mom-api.smartclide-mom:8080
          predicates:
            - Path=/mom/**
        # MoM Websocket
        - id: mom-websocket
          uri: ws://mom-api.smartclide-mom:8080
          predicates:
            - Path=/websocket
        # SmartCLIDE DB
        - id: smartclide-db
          uri: http://db-api.smartclide-db:8080
          predicates:
            - Path=/smartclide-db/**
          filters:
            - RewritePath=/smartclide-db/?(?<segment>.*), /$\{segment}
        # SmartAssistant
        - id: smart-assistant
          uri: http://dle-smartassistant.smartclide-dle:5000
          predicates:
            - Path=/smart-assistant/**
          filters:
            - RewritePath=/smart-assistant/?(?<segment>.*), /smartclide/v1/smartassistant/$\{segment}
        # CICD
        - id: cicd
          uri: http://cicd.smartclide-cicd:8080
          predicates:
            - Path=/cicd/**
          filters:
            - RewritePath=/cicd/?(?<segment>.*), /cicd/$\{segment}
        # Deployment Interpreter
        - id: deployment-interpreter
          uri: http://deployment-interpreter.smartclide-deployment-interpreter:8080
          predicates:
            - Path=/deployment-interpreter/**
          filters:
            - RewritePath=/deployment-interpreter/?(?<segment>.*), /$\{segment}
        # Deployment Service
        - id: deployment-service
          uri: http://deployment-service.smartclide-deployment-service:3000
          predicates:
            - Path=/deployment-service/**
          filters:
            - RewritePath=/deployment-service/?(?<segment>.*), /$\{segment}
        # External Project Importer
        - id: external-project-importer
          uri: http://external-project-importer.smartclide-external-project-importer:8080
          predicates:
            - Path=/external-project-importer/**
          filters:
            - RewritePath=/external-project-importer/?(?<segment>.*), /$\{segment}
        # DLE
        - id: dle
          uri: http://dle-dle.smartclide-dle:5001
          predicates:
            - Path=/dle/**
          filters:
            - RewritePath=/dle/?(?<segment>.*), /smartclide/v1/dle/$\{segment}
        # Iamodeler
        - id: iamodeler
          uri: http://dle-dle.smartclide-dle:5001
          predicates:
            - Path=/iamodeler/**
          filters:
            - RewritePath=/iamodeler/?(?<segment>.*), /smartclide/v1/iamodeler/$\{segment}
        # Service Discovery
        - id: service-discovery
          uri: http://service-discovery.smartclide-service-discovery:2020
          predicates:
            - Path=/service-discovery/**
          filters:
            - RewritePath=/service-discovery/?(?<segment>.*), /servicediscovery/v1/$\{segment}
        # Service Creation
        - id: service-creation
          uri: http://service-creation.smartclide-service-creation:8080
          predicates:
            - Path=/service-creation/**
          filters:
            - RewritePath=/service-creation/?(?<segment>.*), /$\{segment}
        # Service Creation Test Generation
        - id: service-creation-test-generation
          uri: http://service-creation-test-generation.smartclide-service-creation:8080
          predicates:
            - Path=/service-creation-test-generation/**
          filters:
            - RewritePath=/service-creation-test-generation/?(?<segment>.*), /$\{segment}
        # TD Interest
        - id: td-interest
          uri: http://td-interest.smartclide-td:8080
          predicates:
            - Path=/td-interest/**
          filters:
            - RewritePath=/td-interest/?(?<segment>.*), /api/$\{segment}
        # TD Principal
        - id: td-principal
          uri: http://td-principal.smartclide-td:8555
          predicates:
            - Path=/td-principal/**
          filters:
            - RewritePath=/td-principal/?(?<segment>.*), /api/$\{segment}
        # TD Reusability
        - id: td-reusability
          uri: http://td-reusability.smartclide-td:8080
          predicates:
            - Path=/td-reusability/**
          filters:
            - RewritePath=/td-reusability/?(?<segment>.*), /api/$\{segment}
        # Architectural Patterns Rest API
        - id: architectural-patterns
          uri: http://architectural-patterns.smartclide-architectural-patterns:8080
          predicates:
            - Path=/architectural-patterns/**
          filters:
            - RewritePath=/architectural-patterns/?(?<segment>.*), /$\{segment}
