name: ci

on:
  push:
    branches: [ main ]

jobs:
  publish_mom_image:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Publish Docker Image
        run: |
          # login to GitHub Container Registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          # build image
          docker build . --tag ghcr.io/eclipse-opensmartclide/smartclide/api_gateway:$(date +'%Y-%m-%d')
          # push image
          docker push ghcr.io/eclipse-opensmartclide/smartclide/api_gateway:$(date +'%Y-%m-%d')
